habr_proj/authapp/urls.py
from django.urls import path

from authapp.views import LoginUserView, LogoutUserView, RegisterUserView, VerifyUserView, UpdateProfileView, \
    UserProfileDetailView
from posts.views import PostDetailProfileView

app_name = 'authapp'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('verify/<key>/', VerifyUserView.as_view(), name='verify'),
    path('verify/<key>/', VerifyUserView.as_view(), name='verify'),
    path('profile/', UpdateProfileView.as_view(), name='profile'),
    path('profile/<pk>/', UserProfileDetailView.as_view(), name='user_profile'),

    path('profile/post-detail/<pk>/', PostDetailProfileView.as_view(), name='post_detail_profile')
]

habr_proj/habr_proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import Index, SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='main'),
    path('search/', SearchView.as_view(), name='search'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('notify/', include('notifyapp.urls', namespace='notify')),
    path('subscribe/', include('subscribe.urls', namespace='subscribe')),
    path('settings/', include('settings.urls', namespace='settings')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

habr_proj/posts/urls.py
from django.urls import path

from posts import views as posts
from posts.views import PostListCategoryView, CommentDeleteView, CommentUpdateView, PostModerateView, \
    PostModerateListView, like_or_dislike

app_name = 'posts'

urlpatterns = [
    path('create/', posts.PostCreateView.as_view(), name='post_create'),
    path('list/', posts.PostListView.as_view(), name='post_list'),
    path('delete/<pk>/', posts.PostDeleteView.as_view(), name='post_delete'),
    path('update/<pk>/', posts.PostUpdateView.as_view(), name='post_update'),
    path('publish/<pk>/', posts.PostPublishView.as_view(), name='post_publish'),

    path('detail/<pk>/', posts.PostDetailView.as_view(), name='post_detail'),
    path('category/<pk>/', PostListCategoryView.as_view(), name='post_category'),

    path('comment/delete/<pk>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('comment/update/<pk>/', CommentUpdateView.as_view(), name='comment_update'),

    path('moderate/<pk>/<mod_result>/', PostModerateView.as_view(), name='post_moderate'),
    path('moderatelist/', PostModerateListView.as_view(), name='moderate_list'),

    path('likes/<pk>/', like_or_dislike, name='likes')
]

habr_proj/subscribe/urls.py
from django.urls import path

from subscribe.views import SubscribeView, UnSubscribeView, FollowersView, SubscribesView

app_name = 'subscribe'

urlpatterns = [
    path('subscribes/<pk>/', SubscribeView.as_view(), name='subscribes'),
    path('unsubscribes/<pk>/', UnSubscribeView.as_view(), name='unsubscribes'),

    path('followers/<pk>/', FollowersView.as_view(), name='followers'),
    path('view_subscribes/<pk>/', SubscribesView.as_view(), name='view_subscribes'),
]

habr_proj/authapp/models.py
from uuid import uuid4

from django.contrib.auth.models import AbstractUser
from django.db import models


class HabrUser(AbstractUser):
    uid = models.UUIDField(primary_key=True, default=uuid4)
    avatar = models.ImageField(upload_to='user_avatar', blank=True, verbose_name='Аватар')
    birthday = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    about_me = models.TextField(max_length=512, blank=True, verbose_name='Обо мне')
    specialization = models.CharField(max_length=150, blank=True, null=True, verbose_name='Специализация')

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def activate_user(self):
        self.is_active = True
        self.save()

habr_proj/authapp/forms.py
import datetime

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from authapp.models import HabrUser


class HabrUserLoginForm(AuthenticationForm):
    class Meta:
        model = HabrUser
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class HabrUserRegisterForm(UserCreationForm):
    class Meta:
        model = HabrUser
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(HabrUserRegisterForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_email(self):
        data = self.cleaned_data['email']
        email_list = list(HabrUser.objects.values('email'))
        for i in email_list:
            if data == i.get('email'):
                raise forms.ValidationError('Такой email уже существует')

        return data

    def clean_username(self):
        data = self.cleaned_data['username']
        username_list = list(HabrUser.objects.values('username'))
        for i in username_list:
            if data == i.get('username'):
                raise forms.ValidationError('Такой ник уже существует')
        return data

    def clean_password(self):
        pass_1 = self.cleaned_data['password1']
        pass_2 = self.cleaned_data['password2']
        if pass_1 != pass_2:
            raise forms.ValidationError('Пароли не совпадают')
        return pass_1

    def save(self, *args, **kwargs):
        user = super().save(*args, **kwargs)
        user.is_active = False
        user.save()
        return user


class HabrUserEditForm(UserChangeForm):
    class Meta:
        model = HabrUser
        fields = ('username', 'first_name', 'last_name', 'email', 'birthday', 'avatar', 'specialization', 'about_me', 'password',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''
            if field_name == 'password':
                field.widget = forms.HiddenInput()

habr_proj/authapp/views.py
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import CreateView, UpdateView, TemplateView, DetailView
from authapp.forms import HabrUserLoginForm, HabrUserRegisterForm, HabrUserEditForm
from authapp.models import HabrUser
from authapp.tasks import send_verify_email_task
from posts.models import PostCategory, Posts
from subscribe.models import SubscribeModel


class LoginUserView(LoginView):
    template_name = 'authapp/auth-login.html'
    form_class = HabrUserLoginForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Вход'
        context_data['categories'] = PostCategory.objects.filter()
        return context_data


class LogoutUserView(LogoutView):
    template_name = 'authapp/logout.html'


class RegisterUserView(CreateView):
    form_class = HabrUserRegisterForm
    template_name = 'authapp/auth-register.html'
    success_url = reverse_lazy("auth:login")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        context['categories'] = PostCategory.objects.filter()
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            new_user = form.save()
            send_verify_email_task(new_user.uid)
            return HttpResponseRedirect(reverse('auth:login'))
        return super(RegisterUserView, self).post(request, *args, **kwargs)


class VerifyUserView(View):

    def get(self, request, key):
        user = HabrUser.objects.filter(uid=key).first()
        if user:
            user.activate_user()
            auth.login(request, user)
        return render(request, 'authapp/register_result.html')


class UpdateProfileView(UpdateView):
    form_class = HabrUserEditForm
    template_name = 'authapp/profile.html'
    success_url = reverse_lazy('authapp:profile')

    def get_object(self, queryset=None):
        if self.request.user.is_anonymous:
            return None
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактирование профиля'
        context['categories'] = PostCategory.objects.filter()
        context['posts_count'] = Posts.objects.filter(user=self.request.user, is_published=True,is_active=True).count()
        context['followers'] = SubscribeModel.objects.filter(user=self.request.user).count()
        context['following'] = SubscribeModel.objects.filter(subscriber=self.request.user).count()
        return context

    def get(self, request, *args, **kwargs):
        if self.request.user.is_anonymous:
            return HttpResponseRedirect(reverse('auth:login'))
        return super(UpdateProfileView, self).get(request, *args, **kwargs)


class UserProfileDetailView(LoginRequiredMixin, DetailView):
    login_url = reverse_lazy('authapp:login')
    template_name = 'authapp/profile_detail.html'

    def get_queryset(self):
        return HabrUser.objects.filter(pk=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Профиль'
        context['user_detail'] = self.get_queryset().first()
        context['count_posts'] = Posts.objects.filter(user__pk=self.kwargs.get('pk'), is_published=True, is_active=True).count()
        context['posts'] = Posts.objects.filter(user__pk=self.kwargs.get('pk'), is_published=True, is_active=True).order_by('-created_at')
        subscriber = SubscribeModel.objects.filter(user=self.kwargs.get('pk'), subscriber=self.request.user)
        if subscriber:
            context['is_subscriber'] = True
        else:
            context['is_subscriber'] = False

        context['followers'] = SubscribeModel.objects.filter(user=self.kwargs.get('pk')).count()
        context['following'] = SubscribeModel.objects.filter(subscriber=self.kwargs.get('pk')).count()
        return context

habr_proj/authapp/templates/authapp/auth-login.html
{% extends 'authapp/base_register.html' %}
{% load static %}

{% block content %}
    <div id="app">
        <section class="section">
            <div class="container mt-5">
                <div class="row">
                    <div class="col-12 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-6 offset-lg-3 col-xl-4 offset-xl-4">
                        <div class="login-brand">
                            <img src="{% static 'assets/img/stisla-fill.svg' %}" alt="logo" width="100"
                                 class="shadow-light rounded-circle">
                        </div>

                        <div class="card card-primary">
                            <div class="card-header"><h4>Вход</h4></div>

                            <div class="card-body">
                                <form method="POST" action="{% url 'auth:login' %}" class="needs-validation"
                                      novalidate="">
                                    {% csrf_token %}
                                    {% if next %}
                                        <input type="hidden" name="next" value="{{ next }}">
                                    {% endif %}
                                    {{ form.as_p }}


                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary btn-lg btn-block" tabindex="4">
                                            Вход
                                        </button>
                                    </div>
                                </form>


                            </div>
                        </div>
                        <div class="mt-5 text-muted text-center">
                            Нет аккаунта? <a href="{% url 'auth:register' %}">Зарегистрироваться</a>
                        </div>
                        <div class="simple-footer">
                            Copyright &copy; Stisla 2018
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

habr_proj/authapp/templates/authapp/auth-register.html
{% extends 'authapp/base_register.html' %}
{% load static %}

{% block content %}
    <div id="app">
        <section class="section">
            <div class="container mt-5">
                <div class="row">
                    <div class="col-12 col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-8 offset-lg-2 col-xl-8 offset-xl-2">
                        <div class="login-brand">
                            <img src="{% static 'assets/img/stisla-fill.svg' %}" alt="logo" width="100"
                                 class="shadow-light rounded-circle">
                        </div>
                        <div class="card card-primary">
                            <div class="card-header"><h4>Регистрация</h4></div>
                            <div class="card-body">
                                <form method="POST" action="{% url 'auth:register' %}">
                                    {% csrf_token %}
                                    {% if next %}
                                        <input type="hidden" name="next" value="{{ next }}">
                                    {% endif %}
                                 {{ form.as_p }}
                                    <div class="form-group">
                                        <div class="custom-control custom-checkbox">
                                            <input type="checkbox" name="agree" class="custom-control-input" id="agree">
                                            <label class="custom-control-label" for="agree">I agree with the terms and
                                                conditions</label>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary btn-lg btn-block">
                                            Регистрация
                                        </button>
                                    </div>
                                </form>
                            </div>
                        </div>
                        <div class="simple-footer">
                            Copyright &copy; Logo 2022
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
{% endblock %}

habr_proj/authapp/templates/authapp/base_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
  <title></title>

  <!-- General CSS Files -->
  <link rel="stylesheet" href="{% static 'assets/modules/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'assets/modules/fontawesome/css/all.min.css' %}">

  <!-- CSS Libraries -->
  <link rel="stylesheet" href="{% static 'assets/modules/jquery-selectric/selectric.css' %}">

  <!-- Template CSS -->
  <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'assets/css/components.css' %}">
<!-- Start GA -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-94034622-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-94034622-3');
</script>
<!-- /END GA --></head>

<body>
{% block content %}
{% endblock %}


  <!-- General JS Scripts -->
  <script src="{% static 'assets/modules/jquery.min.js' %}"></script>
  <script src="{% static 'assets/modules/popper.js' %}"></script>
  <script src="{% static 'assets/modules/tooltip.js' %}"></script>
  <script src="{% static 'assets/modules/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'assets/modules/nicescroll/jquery.nicescroll.min.js' %}"></script>
  <script src="{% static 'assets/modules/moment.min.js' %}"></script>
  <script src="{% static 'assets/js/stisla.js' %}"></script>

  <!-- JS Libraies -->
  <script src="{% static 'assets/modules/jquery-pwstrength/jquery.pwstrength.min.js' %}"></script>
  <script src="{% static 'assets/modules/jquery-selectric/jquery.selectric.min.js' %}"></script>

  <!-- Page Specific JS File -->
  <script src="{% static 'assets/js/page/auth-register.js' %}"></script>

  <!-- Template JS File -->
  <script src="{% static 'assets/js/scripts.js' %}"></script>
  <script src="{% static 'assets/js/custom.js' %}"></script>
</body>
</html>

habr_proj/authapp/templates/authapp/logout.html
{% extends 'mainapp/new_base.html' %}
{% load static %}

{% block content %}
    <section class="section">
    <div class="card">
        <div class="card-header">
            <h4> Выполнен выход пользователя</h4>
        </div>
        <div class="card-body">
        <span class="d-inline-block">
                       <a href="{% url 'main' %}" class="btn btn-primary">На главную</a>
                    </span>
        </div>
    </div>
    </section>

{% endblock %}

habr_proj/authapp/templates/authapp/profile.html
{% extends 'mainapp/new_base.html' %}
{% load static %}

{% block content %}
    <section class="section">
        {% include 'authapp/includes/inc_profile_header.html' %}
        <div class="section-body">
            <h2 class="section-title">Hi, {{ user.username }}!</h2>
            <p class="section-lead">
                Изменить информацию о себе на этой странице.
            </p>

            <div class="row mt-sm-4">
                <div class="col-12 col-md-12 col-lg-5">
                    <div class="card profile-widget">
                        <div class="profile-widget-header">
                            {% if user.avatar %}
                                <img alt="image" src="/media/{{ user.avatar }}"
                                 class="rounded-circle profile-widget-picture" style="height: 100px;width: 100px;">
                            {% else %}
                                 <img alt="image" src="{% static 'assets/img/avatar/avatar-1.png' %}"
                                 class="rounded-circle profile-widget-picture">
                            {% endif %}
                            <div class="profile-widget-items">
                                <div class="profile-widget-item">
                                    <div class="profile-widget-item-label">Посты</div>
                                    <div class="profile-widget-item-value">{{ posts_count }}</div>
                                </div>
                                <div class="profile-widget-item">
                                    <div class="profile-widget-item-label"><a href="{% url 'subscribe:followers' user.pk %}">Followers</a></div>
                                    <div class="profile-widget-item-value">{{ followers }}</div>
                                </div>
                                <div class="profile-widget-item">
                                    <div class="profile-widget-item-label"><a href="{% url 'subscribe:view_subscribes' user.pk %}">Following</a></div>
                                    <div class="profile-widget-item-value">{{ following }}</div>
                                </div>
                            </div>
                        </div>
                        <div class="profile-widget-description">
                            <div class="profile-widget-name">{{ user.first_name }} {{ user.last_name }}
                                <div class="text-muted d-inline font-weight-normal">
                                    <div class="slash"></div>
                                    {{ user.specialization }}
                                </div>
                            </div>
                            {{ user.about_me }}
                        </div>
                        <div class="card-footer text-center">
                            <div class="font-weight-bold mb-2"></div>
                            <a href="#" class="btn btn-social-icon btn-facebook mr-1">
                                <i class="fab fa-facebook-f"></i>
                            </a>
                            <a href="#" class="btn btn-social-icon btn-twitter mr-1">
                                <i class="fab fa-twitter"></i>
                            </a>
                            <a href="#" class="btn btn-social-icon btn-github mr-1">
                                <i class="fab fa-github"></i>
                            </a>
                            <a href="#" class="btn btn-social-icon btn-instagram">
                                <i class="fab fa-instagram"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-12 col-lg-7">
                    <div class="card col-12">
                        <form method="post" class="needs-validation" action="{% url 'auth:profile' %} "
                              novalidate=""  enctype="multipart/form-data">
                            <div class="card-header">
                                <h4>Редактирование профиля</h4>
                            </div>
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="card-footer text-right">
                                <button class="btn btn-primary">Сохранить изменения</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

habr_proj/authapp/templates/authapp/profile_detail.html
{% extends 'mainapp/new_base.html' %}
{% load static %}

{% block content %}
    <section class="section">
        <div class="section-header">
            <div class="section-header-back">
                <a href="{% url 'main' %}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
            </div>
            <h1>Профиль {{ user_detail.username }}</h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="{% url 'main' %}">Главная</a></div>
                <div class="breadcrumb-item">Профиль {{ user_detail.username }}</div>
            </div>
        </div>
        <div class="section-body">
             <div class="col-12 col-sm-12">
                <div class="card profile-widget">
                  <div class="profile-widget-header">
                      {% if user_detail.avatar %}
                          <img alt="image" src="/media/{{ user_detail.avatar }}" class="rounded-circle profile-widget-picture" width="100" height="100">
                      {% else %}
                          <img alt="image" src="{% static 'assets/img/avatar/avatar-1.png' %}" class="rounded-circle profile-widget-picture">
                      {% endif %}
                    <div class="profile-widget-items">
                      <div class="profile-widget-item">
                        <div class="profile-widget-item-label">Хабы</div>
                        <div class="profile-widget-item-value">{{ count_posts }}</div>
                      </div>
                      <div class="profile-widget-item">
                        <div class="profile-widget-item-label"><a href="{% url 'subscribe:followers' user_detail.pk %}">Followers</a></div>
                        <div class="profile-widget-item-value">{{ followers }}</div>
                      </div>
                      <div class="profile-widget-item">
                        <div class="profile-widget-item-label"><a href="{% url 'subscribe:view_subscribes' user_detail.pk %}">Following</a></div>
                        <div class="profile-widget-item-value">{{ following }}</div>
                      </div>
                    </div>
                  </div>
                  <div class="profile-widget-description pb-0">
                    <div class="profile-widget-name">{{ user_detail.first_name }} {{ user_detail.last_name }}<div class="text-muted d-inline font-weight-normal"><div class="slash"></div>
                        {% if user_detail.specialization %}
                            {{ user_detail.specialization }}
                            {% else %}
                        {% endif %}
                    </div></div>
                    <p>{{ user_detail.about_me }}</p>
                  </div>

                  <div class="card-footer text-center pt-0">
{#                    <div class="font-weight-bold mb-2 text-small">Подписаться на {{ user_detail.first_name }} {{ user_detail.last_name }}</div>#}
                      {% if is_subscriber %}
                    <a href="{% url 'subscribe:unsubscribes' user_detail.pk %}" class="btn btn-danger mt-3">Отписаться</a>
                      {% else %}
                       <a href="{% url 'subscribe:subscribes' user_detail.pk %}" class="btn btn-primary mt-3">Подписаться</a>
                      {% endif %}
                  </div>
                </div>
              </div>

        <div class="row">
             {% for post in posts %}
        <div class="col-12 col-md-4 col-lg-4">
                    <article class="article article-style-c" style="height: 500px">
                        <div class="article-header">
                            {% if not post.image %}
                                <div class="article-image" data-background="{% static 'assets/img/news/img13.jpg' %}">
                            {% else %}
                                <div class="article-image" data-background="/media/{{ post.image }}">
                            {% endif %}
                            </div>
                            </div>
                            <div class="article-details">
                                <div class="article-category"><a
                                        href="{% url 'posts:post_category' post.category.pk %}">{{ post.category.name }}</a>
                                    <div class="bullet"></div>
                                    <a href="#">{{ post.created_at.date }}
                                        в {{ post.created_at.time.hour }}:{{ post.created_at.time.minute }}</a></div>
                                <div class="article-title">
                                    <h2><a href="{% url 'posts:post_detail' post.pk %}">{{ post.title }}</a></h2>
                                </div>
                                <p style="overflow: hidden;display: -webkit-box;-webkit-line-clamp: 3;-webkit-box-orient: vertical;line-height: 1.3em;height: 3.9em;">
                                    {{ post.body }}</p>
                                <div class="article-user">
                                    {% if post.user.avatar %}
                                        <img alt="image" src="/media/{{ post.user.avatar }}"
                                             style="width: 45px;height: 45px;">
                                    {% else %}
                                        <img alt="image" src="{% static 'assets/img/avatar/avatar-1.png' %}">
                                    {% endif %}
                                    <div class="article-user-details">
                                        <div class="user-detail-name">
                                            {% if post.user.pk == user.pk %}
                                                <a href="{% url 'auth:profile' %}">{{ post.user.username }}</a>
                                            {% else %}
                                                <a href="{% url 'auth:user_profile' post.user.pk %}">{{ post.user.username }}</a>
                                            {% endif %}
                                        </div>
                                        {% if post.user.specialization %}
                                            <div class="text-job">{{ post.user.specialization }}</div>
                                        {% else %}
                                            <div class="text-job">{{ post.user.specialization }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                    </article>
                </div>
        {% endfor %}
        </div>
        </div>

    </section>
{% endblock %}

habr_proj/authapp/templates/authapp/register_result.html
{% extends 'mainapp/new_base.html' %}
{% load static %}

{% block content %}
    <div class="card">
        <div class="card-header">
            {% if user.is_authenticated %}
        <h1>Поздравляем!</h1>
        <h2>Добро пожаловать!</h2>

    {% else %}
        <h1>Ошибка!</h1>
        <h2>Что-то пошло не так!</h2>
    {% endif %}
        </div>
        <div class="card-body">
        <span class="d-inline-block">
                       <a href="{% url 'main' %}" class="btn btn-primary">На главную</a>
                    </span>
        </div>
    </div>
{% endblock %}