habr_proj/authapp/urls.py
from django.urls import path

from authapp.views import LoginUserView, LogoutUserView, RegisterUserView, VerifyUserView, UpdateProfileView, \
    UserProfileDetailView
from posts.views import PostDetailProfileView

app_name = 'authapp'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('verify/<key>/', VerifyUserView.as_view(), name='verify'),
    path('verify/<key>/', VerifyUserView.as_view(), name='verify'),
    path('profile/', UpdateProfileView.as_view(), name='profile'),
    path('profile/<pk>/', UserProfileDetailView.as_view(), name='user_profile'),

    path('profile/post-detail/<pk>/', PostDetailProfileView.as_view(), name='post_detail_profile')
]

habr_proj/habr_proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import Index, SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='main'),
    path('search/', SearchView.as_view(), name='search'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('notify/', include('notifyapp.urls', namespace='notify')),
    path('subscribe/', include('subscribe.urls', namespace='subscribe')),
    path('settings/', include('settings.urls', namespace='settings')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

habr_proj/posts/urls.py
from django.urls import path

from posts import views as posts
from posts.views import PostListCategoryView, CommentDeleteView, CommentUpdateView, PostModerateView, \
    PostModerateListView, like_or_dislike

app_name = 'posts'

urlpatterns = [
    path('create/', posts.PostCreateView.as_view(), name='post_create'),
    path('list/', posts.PostListView.as_view(), name='post_list'),
    path('delete/<pk>/', posts.PostDeleteView.as_view(), name='post_delete'),
    path('update/<pk>/', posts.PostUpdateView.as_view(), name='post_update'),
    path('publish/<pk>/', posts.PostPublishView.as_view(), name='post_publish'),

    path('detail/<pk>/', posts.PostDetailView.as_view(), name='post_detail'),
    path('category/<pk>/', PostListCategoryView.as_view(), name='post_category'),

    path('comment/delete/<pk>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('comment/update/<pk>/', CommentUpdateView.as_view(), name='comment_update'),

    path('moderate/<pk>/<mod_result>/', PostModerateView.as_view(), name='post_moderate'),
    path('moderatelist/', PostModerateListView.as_view(), name='moderate_list'),

    path('likes/<pk>/', like_or_dislike, name='likes')
]

habr_proj/posts/forms.py
from django import forms

from posts.models import Posts, Links, Comment


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Posts
        exclude = ('uid', 'created_at', 'updated_at', 'is_active', 'user', 'is_moderated', 'status_moderation', 'views')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_published':
                field.widget.attrs['class'] = 'colorinput-color bg-primary'
            else:
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class PostUpdateForm(forms.ModelForm):
    class Meta:
        model = Posts
        exclude = ('uid', 'created_at', 'updated_at', 'is_active', 'user','is_moderated','status_moderation', 'views')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_published':
                field.widget.attrs['class'] = 'colorinput-color bg-primary'
            else:
                field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    def clean_body(self):
        data = self.cleaned_data['body']
        if 'script' in data:
            raise forms.ValidationError('Нельзя использовать script на странице')
        return data


class LinksCreateForm(forms.ModelForm):
    class Meta:
        model = Links
        fields = ('name', 'link',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class CommentCreateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_body',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class CommentUpdateForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment_body',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

habr_proj/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.db.models import F
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, DetailView

from posts.forms import PostCreateForm, CommentCreateForm, PostUpdateForm, CommentUpdateForm
from posts.models import Posts, PostCategory, Comment, PostsLikes


def get_posts_in_category(pk):
    if settings.LOW_CACHE:
        key = 'posts_in_category'
        posts_in_category = cache.get(key)
        if posts_in_category is None:
            posts_in_category = Posts.objects.filter(category__pk=pk,
                                                     is_active=True,
                                                     is_published=True,
                                                     is_moderated=True,
                                                     status_moderation=Posts.POST_MODERATE
                                                     ).select_related().order_by('-created_at')
            cache.set(key, posts_in_category)
        return posts_in_category
    return Posts.objects.filter(category__pk=pk, is_active=True, is_published=True, is_moderated=True,
                                status_moderation=Posts.POST_MODERATE).select_related().order_by('-created_at')


def get_categories():
    if settings.LOW_CACHE:
        key = 'post_category'
        post_category = cache.get(key)
        if post_category is None:
            post_category = PostCategory.objects.all()
            cache.set(key, post_category)
        return post_category
    return PostCategory.objects.all()


def get_comments(pk):
    return Comment.objects.filter(post__pk=pk, is_active=True).order_by('-created_at')


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Posts
    form_class = PostCreateForm
    template_name = 'posts/posts_form.html'
    success_url = reverse_lazy('posts:post_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Хаб/создание'
        context_data['create_update'] = 'Создание Хаба'
        context_data['create_update_text'] = 'создать новый'
        return context_data

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            user = form.save(commit=False)
            user.user = request.user
            user.save()
            return HttpResponseRedirect(reverse('posts:post_list'))
        return super(PostCreateView, self).post(request, *args, **kwargs)


class PostListView(LoginRequiredMixin, ListView):
    model = Posts

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user, is_active=True).order_by(
            '-created_at').select_related()

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = f'Хабы {self.request.user}'
        context_data['categories'] = get_categories()

        return context_data


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Posts
    success_url = reverse_lazy('posts:post_list')


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Posts
    template_name = 'posts/posts_form_update.html'
    form_class = PostUpdateForm
    success_url = reverse_lazy('posts:post_list')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Хаб/редактирование'
        context_data['create_update'] = 'Редактирование Хаба'
        context_data['create_update_text'] = 'редактировать'
        context_data['pk'] = self.kwargs.get('pk')
        return context_data
    #
    # def post(self, request, *args, **kwargs):
    #     form = self.get_form()
    #     if form.is_valid():
    #         user = form.save(commit=False)
    #         user.user = request.user
    #         # user.is_moderated = False
    #         # user.status_moderation = Posts.POST_MODERATE
    #         user.save()
    #         # return HttpResponseRedirect(reverse('posts:post_list'))
    #     return super(PostUpdateView, self).post(request, *args, **kwargs)


class PostPublishView(LoginRequiredMixin, DetailView):

    def get_queryset(self):
        return Posts.objects.filter(pk=self.kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        post = self.get_queryset().first()
        if post.is_published:
            post.is_published = False
            post.save()
        else:
            post.is_published = True
            post.save()
        return HttpResponseRedirect(reverse('posts:post_list'))


class PostDetailView(UpdateView):
    template_name = 'posts/post_detail.html'
    form_class = CommentCreateForm

    def get_queryset(self):
        return Posts.objects.filter(pk=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Хаб'
        context_data['post'] = self.get_queryset().first()
        context_data['comment_title'] = 'Написать комментарий'
        context_data['comments'] = get_comments(self.kwargs.get('pk'))
        return context_data

    def post(self, request, *args, **kwargs):
        reverse_param = reverse('posts:post_detail', kwargs={'pk': self.kwargs.get('pk')})
        if not self.request.user.is_authenticated:
            return HttpResponseRedirect('%s?next=%s' % (reverse('auth:login'), reverse_param))
        form = self.get_form()
        if form.is_valid():
            user = form.save(commit=False)
            user.user = request.user
            user.post = self.get_queryset()[0]
            user.save()
            return HttpResponseRedirect(reverse_param)
        return super(PostDetailView, self).post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        post = self.get_queryset().first()
        post.views = F('views') + 1
        post.save()
        return super().get(request, *args, **kwargs)


class PostDetailProfileView(DetailView):
    template_name = 'posts/posts_detail_profile.html'

    def get_queryset(self):
        return Posts.objects.filter(pk=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Хаб'
        context_data['post'] = self.get_queryset().first()
        return context_data


class PostListCategoryView(ListView):
    model = Posts
    template_name = 'posts/posts_category_list.html'
    paginate_by = 4

    def get_queryset(self):
        queryset = super().get_queryset()
        category_pk = self.kwargs.get('pk')
        if category_pk != 0:
            queryset = get_posts_in_category(category_pk)

        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        category = PostCategory.objects.filter(pk=self.kwargs.get('pk'))[0]
        context_data['title'] = f'Хабы {category}'
        context_data['category_name'] = category
        context_data['categories'] = get_categories()

        return context_data


class PostModerateView(LoginRequiredMixin, DetailView):

    def get_queryset(self):
        return Posts.objects.filter(pk=self.kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        post = self.get_queryset().first()
        mod_result = self.kwargs.get('mod_result')
        if mod_result == 'ok':
            post.is_moderated = True
            post.status_moderation = 'PM'
            post.save()
        else:
            post.is_moderated = False
            post.status_moderation = 'BLC'
            post.save()
        return HttpResponseRedirect(reverse('posts:post_detail', kwargs={'pk': self.kwargs.get('pk')}))


class PostModerateListView(LoginRequiredMixin, ListView):
    model = Posts
    template_name = 'posts/posts_moderate_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(is_active=True, is_moderated=False).order_by(
            '-created_at').select_related()

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = f'Хабы на модерацию'
        context_data['categories'] = get_categories()

        return context_data


class CommentDeleteView(LoginRequiredMixin, DetailView):
    model = Comment

    def get_queryset(self):
        return Comment.objects.filter(pk=self.kwargs.get('pk')).first()

    def get(self, request, *args, **kwargs):
        comment = self.get_queryset()
        comment.is_active = False
        comment.save()
        return HttpResponseRedirect(reverse('posts:post_detail', kwargs={'pk': comment.post.pk}))


class CommentUpdateView(LoginRequiredMixin, UpdateView):
    form_class = CommentUpdateForm
    template_name = 'posts/post_detail.html'

    def get_queryset(self):
        return Comment.objects.filter(pk=self.kwargs.get('pk'))

    def get_success_url(self):
        comment = self.get_queryset().first()
        return reverse_lazy('posts:post_detail', kwargs={'pk': comment.post.pk})


@login_required(login_url='/auth/login/')
def like_or_dislike(request, pk):
    if request.is_ajax():
        post = Posts.objects.get(pk=pk)
        like = PostsLikes.objects.filter(for_post=post, user=request.user).first()
        if like:
            if like.is_like:
                print('DISLIKE')
                like.is_like = False
                post.post_like.remove(request.user)
            else:
                print('LIKE')
                like.is_like = True

habr_proj/posts/templates/posts/post_create.html
{% extends 'posts/base.html' %}
{% load static %}

{% block content %}
    <div class="h2 text-center head">
       Создание Хаба
    </div>
    <form class="form-horizontal" action="{% url 'auth:register' %}" method="post">
        {% csrf_token %}
        {% if next %}
            <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        {{ form.as_p }}
        <input type="submit" class="form-control" value="Сохранить">
    </form>
    <hr>
<!--    <button class="btn btn-round form-control">-->
<!--        <a href="{% url 'auth:login' %}" class="">-->
<!--            Войти-->
<!--        </a>-->
<!--    </button>-->
{% endblock %}

habr_proj/posts/templates/posts/post_detail.html
{% extends 'mainapp/new_base.html' %}
{% load static %}

{% block content %}
    <section class="section">
        <div class="section-header">
            <h1>Автор
                {% if post.user.pk == user.pk %}
                    <a href="{% url 'auth:profile' %}">{{ post.user.username }}</a>
                {% else %}
                    <a href="{% url 'auth:user_profile' post.user.pk %}">{{ post.user.username }}</a>
                {% endif %}
            </h1>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="{% url 'main' %}">Главная</a></div>
                <div class="breadcrumb-item">Хаб</div>
            </div>
        </div>
        <div class="">
            <article class="article article-style-c">
                <div class="article-header">
                    {% if not post.image.url %}
                        <div class="article-image" data-background="{% static 'assets/img/news/img13.jpg' %}">
                    {% else %}
                        <div class="article-image" data-background="/media/{{ post.image }}">
                    {% endif %}
                    </div>
                    </div>
                    <div class="article-details">
                        <div class="article-category"><a href="#">{{ post.category.name }}</a>
                            <div class="bullet"></div>
                            <a href="#">{{ post.created_at.date }}
                                в {{ post.created_at.time.hour }}:{{ post.created_at.time.minute }}</a></div>
                        <div class="article-title">
                            <h2><a href="{% url 'posts:post_detail' post.pk %}">{{ post.title }}</a></h2>
                        </div>
                        <p >
                            {{ post.body|safe }}</p>
                        <div class="article-user">
                            {% if post.user.avatar %}
                                <img alt="image" src="/media/{{ post.user.avatar }}" style="width: 45px;height: 45px;">
                            {% else %}
                                <img alt="image" src="{% static 'assets/img/avatar/avatar-1.png' %}">
                            {% endif %}
                            <div class="article-user-details">
                                <div class="user-detail-name">
                                    {% if post.user.pk == user.pk %}
                                        <a href="{% url 'auth:profile' %}">{{ post.user.username }}</a>
                                    {% else %}
                                        <a href="{% url 'auth:user_profile' post.user.pk %}">{{ post.user.username }}</a>
                                    {% endif %}

                                </div>
                                {% if post.user.specialization %}
                                    <div class="text-job">{{ post.user.specialization }}</div>
                                {% else %}
                                    <div class="text-job"></div>
                                {% endif %}
                            </div>

                        </div>
                    {% include 'mainapp/includes/inc_icons_list.html' %}
                    </div>
                </div>
                {% if user.is_staff %}
                <div class="buttons">
                    {% if not post.is_moderated %}
                        <a href="{% url 'posts:post_moderate' post.pk 'ok' %}" class="btn btn-primary">Прошел модерацию</a>
                    {% endif %}
                    <a href="{% url 'posts:post_moderate' post.pk 'bad' %}" class="btn btn-danger">Не прошел модерацию</a>
                </div>
                {% endif %}
            </article>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>{{ comment_title }}</h4>
                    </div>
                    <div class="card-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% if next %}
                                <input type="hidden" name="next" value="{{ next }}">
                            {% endif %}
                            {{ form.media }}
                            {{ form.as_p }}
                            <input type="submit" class="btn btn-primary add-comment" value="Сохранить" style="margin-top: 20px;">
                        </form>
                    </div>
                </div>
            </div>
        </div>

     <div class="">
                <div class="card">
                  <div class="card-header">
                    <h4>Комментарии</h4>
                  </div>
                  <div class="card-body">
                    <ul class="list-unstyled list-unstyled-border list-unstyled-noborder">
                        {% for item in comments %}
                            <li class="media">
                            {% if item.user.avatar %}
                                <img alt="image" class="mr-3 rounded-circle" width="70" src="/media/{{ item.user.avatar }}">
                                {% else %}
                        <img alt="image" class="mr-3 rounded-circle" width="70" src="{% static 'assets/img/avatar/avatar-1.png' %}">
                                {% endif %}
                        <div class="media-body">
                             {% if item.user.pk == user.pk %}
                                 <div class="media-title mb-1"><a href="{% url 'auth:profile' %}">{{ item.user.username }}</a></div>
                            {% else %}
                                 <div class="media-title mb-1"><a href="{% url 'auth:user_profile' item.user.pk %}">{{ item.user.username }}</a></div>
                            {% endif %}
                          <div class="text-time">{{ item.created_at.date }}
                                        в {{ item.created_at.time.hour }}:{{ item.created_at.time.minute }}</div>
                          <div class="media-description text-muted">{{ item.comment_body | safe }}</div>
                          <div class="media-links">
                              <button class="btn btn-link" id="comment-update">Редактировать</button>
                             <div class="card-body" id="comment-div" style="display: none">
                        <form class="form-horizontal " action="{% url 'posts:comment_update' item.pk %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% if next %}
                                <input type="hidden" name="next" value="{{ next }}">
                            {% endif %}
                            {{ form.media }}
                            {{ form.as_p }}
                            <input type="submit" class="btn btn-primary" value="Сохранить" style="margin-top: 20px;">
                        </form>
                    </div>
                            <div class="bullet"></div>
                            <a href="{% url 'posts:comment_delete' item.pk %}" class="text-danger">Удалить</a>
                          </div>
                        </div>
                      </li>
                        {% endfor %}
                    </ul>
                  </div>
                </div>
              </div>
    </section>
{% endblock %}
{% block ajax %}
    <script src="{% static 'js/addComments.js' %}"></script>
{% endblock %}

habr_proj/posts/templates/posts/posts_confirm_delete.html
{% extends 'mainapp/new_base.html' %}
{% load static %}

{% block content %}

   <div class="post_delete">
       <div class="h1">Уверены, что хотите удалить пост "{{ object.title }}"?</div>

       <div class="buttons">
           <form action="{% url 'posts:post_delete' object.pk %}" method="post">
               {% csrf_token %}
               <input class="btn btn-danger" type="submit" value="удалить">
           </form>

           <button class="btn btn-success">
               <a href="{% url 'posts:post_list' %}">отмена</a>
           </button>
       </div>
   </div>
{% endblock %}

habr_proj/posts/templates/posts/posts_list.html
{% extends 'mainapp/new_base.html' %}
{% load static %}

{% block content %}
    <section class="section">
        <section class="section"></section>
        <div class="section-header">
            <h1>Ваши хабы, {% if user.first_name %}
                {{ user.first_name|title }}
            {% else %}
                Пользователь
            {% endif %}</h1>
            <div class="section-header-button">
                <a href="{% url 'posts:post_create' %}" class="btn btn-primary">Новый хаб</a>
            </div>
            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="{% url 'main' %}">Главная</a></div>
                <div class="breadcrumb-item">Ваши хабы</div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Все хабы</h4>
                    </div>
                    <div class="card-body">
                        <div class="float-right">
                            <form>
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>

                        <div class="clearfix mb-3"></div>

                        <div class="table-responsive">
                            <table class="table table-striped">
                                <tr>
                                    <th>Название</th>
                                    <th>Категория</th>

                                    <th>Дата создания</th>
                                    <th>Статус</th>
                                    <th>Изменить</th>
                                </tr>
                                {% for item in object_list %}
                                    <tr>
                                        <td>{{ item.title }}
                                            <div class="table-links">
                                                <a href="{% url 'auth:post_detail_profile' item.pk %}">Просмотр</a>
                                                <div class="bullet"></div>
                                                <a href="{% url 'posts:post_update' item.pk %}">Редактировать</a>
                                                <div class="bullet"></div>
                                                <a href="{% url 'posts:post_delete' item.pk %}" class="text-danger">Удалить</a>
                                            </div>
                                        </td>
                                        <td>
                                            <a href="#">{{ item.category.name }}</a>
                                        </td>

                                        <td>{{ item.created_at }}</td>
                                        <td>
                                            {% if item.status_moderation == "TO" %}
                                                <div class="badge badge-primary">На модерации</div>
                                                {% elif item.status_moderation == "PM" and item.is_published %}
                                                 <div class="badge  badge-success">Опубликован</div>
                                                {% elif item.status_moderation == "BLC" %}
                                                 <div class="badge badge-danger">Заблокирован</div>
                                            {% elif item.status_moderation == "PM" and item.is_published != True %}
                                                <div class="badge badge-light">Не опубликован</div>
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if item.is_published %}
                                                <a href="{% url 'posts:post_publish' item.pk %}" class="btn">Убрать </a>
                                            {% else %}
                                            <a href="{% url 'posts:post_publish' item.pk %}" class="btn">Опубликовать</a>
                                            {% endif %}

                                        </td>
                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                        {#                    <div class="float-right">#}
                        {#                      <nav>#}
                        {#                        <ul class="pagination">#}
                        {#                          <li class="page-item disabled">#}
                        {#                            <a class="page-link" href="#" aria-label="Previous">#}
                        {#                              <span aria-hidden="true">&laquo;</span>#}
                        {#                              <span class="sr-only">Previous</span>#}
                        {#                            </a>#}
                        {#                          </li>#}
                        {#                          <li class="page-item active">#}
                        {#                            <a class="page-link" href="#">1</a>#}
                        {#                          </li>#}
                        {#                          <li class="page-item">#}
                        {#                            <a class="page-link" href="#">2</a>#}
                        {#                          </li>#}
                        {#                          <li class="page-item">#}
                        {#                            <a class="page-link" href="#">3</a>#}
                        {#                          </li>#}
                        {#                          <li class="page-item">#}
                        {#                            <a class="page-link" href="#" aria-label="Next">#}
                        {#                              <span aria-hidden="true">&raquo;</span>#}
                        {#                              <span class="sr-only">Next</span>#}
                        {#                            </a>#}
                        {#                          </li>#}
                        {#                        </ul>#}
                        {#                      </nav>#}
                        {#                    </div>#}
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}