habr_proj/authapp/urls.py
from django.urls import path

from authapp.views import LoginUserView, LogoutUserView, RegisterUserView, VerifyUserView, UpdateProfileView, \
    UserProfileDetailView
from posts.views import PostDetailProfileView

app_name = 'authapp'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('verify/<key>/', VerifyUserView.as_view(), name='verify'),
    path('verify/<key>/', VerifyUserView.as_view(), name='verify'),
    path('profile/', UpdateProfileView.as_view(), name='profile'),
    path('profile/<pk>/', UserProfileDetailView.as_view(), name='user_profile'),

    path('profile/post-detail/<pk>/', PostDetailProfileView.as_view(), name='post_detail_profile')
]

habr_proj/habr_proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import Index, SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='main'),
    path('search/', SearchView.as_view(), name='search'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('notify/', include('notifyapp.urls', namespace='notify')),
    path('subscribe/', include('subscribe.urls', namespace='subscribe')),
    path('settings/', include('settings.urls', namespace='settings')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

habr_proj/notifyapp/urls.py
from django.urls import path

from notifyapp.views import NotifyConfirmAllView, NotifyListView, NotifyReadView, NotifyDeleteView

app_name = 'notify'

urlpatterns = [
    path('allconfirm/', NotifyConfirmAllView.as_view(), name='confirm_all'),
    path('list/', NotifyListView.as_view(), name='notify_list'),
    path('read/<category>/<pk>/', NotifyReadView.as_view(), name='notify_read'),
    path('delete/<category>/<pk>/', NotifyDeleteView.as_view(), name='notify_delete')
]

habr_proj/posts/urls.py
from django.urls import path

from posts import views as posts
from posts.views import PostListCategoryView, CommentDeleteView, CommentUpdateView, PostModerateView, \
    PostModerateListView, like_or_dislike

app_name = 'posts'

urlpatterns = [
    path('create/', posts.PostCreateView.as_view(), name='post_create'),
    path('list/', posts.PostListView.as_view(), name='post_list'),
    path('delete/<pk>/', posts.PostDeleteView.as_view(), name='post_delete'),
    path('update/<pk>/', posts.PostUpdateView.as_view(), name='post_update'),
    path('publish/<pk>/', posts.PostPublishView.as_view(), name='post_publish'),

    path('detail/<pk>/', posts.PostDetailView.as_view(), name='post_detail'),
    path('category/<pk>/', PostListCategoryView.as_view(), name='post_category'),

    path('comment/delete/<pk>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('comment/update/<pk>/', CommentUpdateView.as_view(), name='comment_update'),

    path('moderate/<pk>/<mod_result>/', PostModerateView.as_view(), name='post_moderate'),
    path('moderatelist/', PostModerateListView.as_view(), name='moderate_list'),

    path('likes/<pk>/', like_or_dislike, name='likes')
]

habr_proj/settings/urls.py
from django.urls import path

from settings.views import HelpView

app_name = 'settings'

urlpatterns = [
    path('help/', HelpView.as_view(), name='help'),
]

habr_proj/mainapp/models.py
from django.db import models

# Create your models here.

habr_proj/mainapp/views.py
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import TemplateView, ListView

from notifyapp.views import get_all_notify, get_all_unread_notify
from posts.models import PostCategory, Posts
from posts.views import get_categories


class Index(ListView):
    model = Posts
    template_name = 'mainapp/index.html'
    paginate_by = 6

    def get_queryset(self):
        return Posts.objects.filter(is_published=True, is_active=True, is_moderated=True,
                                    status_moderation=Posts.POST_MODERATE).order_by('-created_at').select_related()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная'
        context['categories'] = get_categories()
        context['notify'] = get_all_notify(pk=self.request.user.pk)[:5]
        context['notify_count'] = get_all_unread_notify(pk=self.request.user.pk)
        return context


class SearchView(ListView):
    model = Posts
    template_name = 'mainapp/seacrh.html'

    def get_queryset(self):
        query = self.request.GET.get('search')
        queryset = Posts.objects.filter(
            (Q(title__icontains=query) | Q(body__icontains=query)) & Q(is_published=True) & Q(is_active=True) & Q(
                is_moderated=True) & Q(status_moderation=Posts.POST_MODERATE)).order_by('-created_at').select_related()
        print(queryset)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['title'] = 'Результат поиска'
        context['result'] = self.request.GET.get('search')
        return context

habr_proj/mainapp/templates/mainapp/includes/inc_categories_profile.html
{% load static %}
<nav id="profile-nav" class="main-nav__block">
    <div class="main-nav__header main-nav__category">
        <ul class="header-categories">
            <li><a href="/">Все</a></li>
            {% for item in categories %}
                <li><a
                        href="/"
                        {% if request.resolver_match.url_name == item.url %}class="active" {% endif %}
                >{{ item.name }}</a></li>
            {% endfor %}
        </ul>
        <div class="header-profile">
            {% if user.is_authenticated %}
                <img class="user-icon" src="{% static 'img/user.png' %}" alt="" @click="profileListShow=!profileListShow">
                <ul class="profile-menu" v-show="profileListShow">
                    <li><a href="{% url 'auth:profile' %}">Профиль</a></li>
                    <li><a href="{% url 'posts:post_list' %}">Мои публикации</a></li>
                    <li><a href="{% url 'auth:logout' %}">Выйти</a></li>

                </ul>
            {% else %}
                <a href="{% url 'auth:register' %}">Регистрация/</a>
                <a href="{% url 'auth:login' %}">Войти</a>
            {% endif %}
        </div>
    </div>

</nav>

habr_proj/mainapp/templates/mainapp/includes/inc_footer.html
         <footer class="main-footer">
        <div class="footer-left">
          Copyright &copy; 2018 <div class="bullet"></div> Design By <a href="https://nauval.in/">Muhamad Nauval Azhar</a>
        </div>
        <div class="footer-right">

        </div>
      </footer>

habr_proj/mainapp/templates/mainapp/includes/inc_header_catergories.html
{% load static %}
<nav class="navbar navbar-secondary navbar-expand-lg">
        <div class="container">
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a href="#" data-toggle="dropdown" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Категории</span></a>
              <ul class="dropdown-menu">

                    {% for item in categories %}
                         <li class="nav-item"><a href="{% url 'posts:post_category' item.pk %}" class="nav-link"> {{ item.name }}</a></li>
                  {% endfor %}
              </ul>
            </li>
{#            <li class="nav-item">#}
{#              <a href="#" class="nav-link"><i class="far fa-heart"></i><span>Помощь</span></a>#}
{#            </li>#}
{#            <li class="nav-item dropdown">#}
{#              <a href="#" data-toggle="dropdown" class="nav-link has-dropdown"><i class="far fa-clone"></i><span>Multiple Dropdown</span></a>#}
{#              <ul class="dropdown-menu">#}
{#                <li class="nav-item"><a href="#" class="nav-link">Not Dropdown Link</a></li>#}
{#                <li class="nav-item dropdown"><a href="#" class="nav-link has-dropdown">Hover Me</a>#}
{#                  <ul class="dropdown-menu">#}
{#                    <li class="nav-item"><a href="#" class="nav-link">Link</a></li>#}
{#                    <li class="nav-item dropdown"><a href="#" class="nav-link has-dropdown">Link 2</a>#}
{#                      <ul class="dropdown-menu">#}
{#                        <li class="nav-item"><a href="#" class="nav-link">Link</a></li>#}
{#                        <li class="nav-item"><a href="#" class="nav-link">Link</a></li>#}
{#                        <li class="nav-item"><a href="#" class="nav-link">Link</a></li>#}
{#                      </ul>#}
{#                    </li>#}
{#                    <li class="nav-item"><a href="#" class="nav-link">Link 3</a></li>#}
{#                  </ul>#}
{#                </li>#}
{#              </ul>#}
{#            </li>#}
          </ul>
        </div>
      </nav>

habr_proj/mainapp/templates/mainapp/includes/inc_header_main.html
{% load static %}
<nav class="navbar navbar-expand-lg main-navbar">
        <a href="{% url 'main' %}" class="navbar-brand sidebar-gone-hide">Logo</a>
        <a href="#" class="nav-link sidebar-gone-show" data-toggle="sidebar"><i class="fas fa-bars"></i></a>
        <div class="nav-collapse">
          <a class="sidebar-gone-show nav-collapse-toggle nav-link" href="#">
            <i class="fas fa-ellipsis-v"></i>
          </a>
{#          <ul class="navbar-nav">#}
{#            <li class="nav-item active"><a href="#" class="nav-link">Application</a></li>#}
{#            <li class="nav-item"><a href="#" class="nav-link">Report Something</a></li>#}
{#            <li class="nav-item"><a href="#" class="nav-link">Server Status</a></li>#}
{#          </ul>#}
        </div>
        <form class="form-inline ml-auto" action="{% url 'search' %}" method="get">
          <div class="search-element">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250" name="search">
            <button class="btn" type="submit"><i class="fas fa-search"></i></button>
          </div>
        </form>
        <ul class="navbar-nav navbar-right">
{#          <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link nav-link-lg message-toggle beep"><i class="far fa-envelope"></i></a>#}
{#            <div class="dropdown-menu dropdown-list dropdown-menu-right">#}
{#              <div class="dropdown-header">Messages#}
{#                <div class="float-right">#}
{#                  <a href="#">Mark All As Read</a>#}
{#                </div>#}
{#              </div>#}
{#              <div class="dropdown-list-content dropdown-list-message">#}
{#                <a href="#" class="dropdown-item dropdown-item-unread">#}
{#                  <div class="dropdown-item-avatar">#}
{#                    <img alt="image" src="assets/img/avatar/avatar-1.png" class="rounded-circle">#}
{#                    <div class="is-online"></div>#}
{#                  </div>#}
{#                  <div class="dropdown-item-desc">#}
{#                    <b>Kusnaedi</b>#}
{#                    <p>Hello, Bro!</p>#}
{#                    <div class="time">10 Hours Ago</div>#}
{#                  </div>#}
{#                </a>#}
{#                <a href="#" class="dropdown-item dropdown-item-unread">#}
{#                  <div class="dropdown-item-avatar">#}
{#                    <img alt="image" src="assets/img/avatar/avatar-2.png" class="rounded-circle">#}
{#                  </div>#}
{#                  <div class="dropdown-item-desc">#}
{#                    <b>Dedik Sugiharto</b>#}
{#                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>#}
{#                    <div class="time">12 Hours Ago</div>#}
{#                  </div>#}
{#                </a>#}
{#                <a href="#" class="dropdown-item dropdown-item-unread">#}
{#                  <div class="dropdown-item-avatar">#}
{#                    <img alt="image" src="assets/img/avatar/avatar-3.png" class="rounded-circle">#}
{#                    <div class="is-online"></div>#}
{#                  </div>#}
{#                  <div class="dropdown-item-desc">#}
{#                    <b>Agung Ardiansyah</b>#}
{#                    <p>Sunt in culpa qui officia deserunt mollit anim id est laborum.</p>#}
{#                    <div class="time">12 Hours Ago</div>#}
{#                  </div>#}
{#                </a>#}
{#                <a href="#" class="dropdown-item">#}
{#                  <div class="dropdown-item-avatar">#}
{#                    <img alt="image" src="assets/img/avatar/avatar-4.png" class="rounded-circle">#}
{#                  </div>#}
{#                  <div class="dropdown-item-desc">#}
{#                    <b>Ardian Rahardiansyah</b>#}
{#                    <p>Duis aute irure dolor in reprehenderit in voluptate velit ess</p>#}
{#                    <div class="time">16 Hours Ago</div>#}
{#                  </div>#}
{#                </a>#}
{#                <a href="#" class="dropdown-item">#}
{#                  <div class="dropdown-item-avatar">#}
{#                    <img alt="image" src="assets/img/avatar/avatar-5.png" class="rounded-circle">#}
{#                  </div>#}
{#                  <div class="dropdown-item-desc">#}
{#                    <b>Alfa Zulkarnain</b>#}
{#                    <p>Exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>#}
{#                    <div class="time">Yesterday</div>#}
{#                  </div>#}
{#                </a>#}
{#              </div>#}
{#              <div class="dropdown-footer text-center">#}
{#                <a href="#">View All <i class="fas fa-chevron-right"></i></a>#}
{#              </div>#}
{#            </div>#}
{#          </li>#}
            {% if user.is_authenticated %}
          <li class="dropdown dropdown-list-toggle">
              <a href="#" data-toggle="dropdown"
                 {% if notify_count %}class="nav-link notification-toggle nav-link-lg beep"{% else %}class="nav-link notification-toggle nav-link-lg"{% endif %}>
                  <i class="far fa-bell"></i>
              </a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
              <div class="dropdown-header">Уведомления
                <div class="float-right">
                  <a href="{% url 'notify:confirm_all' %}">Отметить все как прочитанные</a>
                </div>
              </div>
              <div class="dropdown-list-content dropdown-list-icons">
                  {% for item in notify %}
                    {% if item.is_read %}
                        <a href="#" class="dropdown-item dropdown-item">
                          <div class="dropdown-item-icon bg-info text-white">
                            <i class="fas fa-bell"></i>
                          </div>
                          <div class="dropdown-item-desc">
                            {{ item.notify_body }}
<!--                            <div class="time">10 Hours Ago</div>-->
                          </div>
                        </a>
                    {% else %}
                        <a href="{% url 'notify:notify_read' item.category item.pk %}" class="dropdown-item dropdown-item-unread">
                          <div class="dropdown-item-icon bg-info text-white">
                            <i class="fas fa-bell"></i>
                          </div>
                          <div class="dropdown-item-desc">
                            {{ item.notify_body }}
<!--                            <div class="time">10 Hours Ago</div>-->
                          </div>
                        </a>
                    {% endif %}
                  {% endfor %}
<!--                  <a href="#" class="dropdown-item dropdown-item-unread">-->
<!--                  <div class="dropdown-item-icon bg-primary text-white">-->
<!--                    <i class="fas fa-code"></i>-->
<!--                  </div>-->
<!--                  <div class="dropdown-item-desc">-->
<!--                    Template update is available now!-->
<!--                    <div class="time text-primary">2 Min Ago</div>-->
<!--                  </div>-->
<!--                </a>-->
<!--                <a href="#" class="dropdown-item">-->
<!--                  <div class="dropdown-item-icon bg-info text-white">-->
<!--                    <i class="far fa-user"></i>-->
<!--                  </div>-->
<!--                  <div class="dropdown-item-desc">-->
<!--                    <b>You</b> and <b>Dedik Sugiharto</b> are now friends-->
<!--                    <div class="time">10 Hours Ago</div>-->
<!--                  </div>-->
<!--                </a>-->
<!--                <a href="#" class="dropdown-item">-->
<!--                  <div class="dropdown-item-icon bg-success text-white">-->
<!--                    <i class="fas fa-check"></i>-->
<!--                  </div>-->
<!--                  <div class="dropdown-item-desc">-->
<!--                    <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>-->
<!--                    <div class="time">12 Hours Ago</div>-->
<!--                  </div>-->
<!--                </a>-->
<!--                <a href="#" class="dropdown-item">-->
<!--                  <div class="dropdown-item-icon bg-danger text-white">-->
<!--                    <i class="fas fa-exclamation-triangle"></i>-->
<!--                  </div>-->
<!--                  <div class="dropdown-item-desc">-->
<!--                    Low disk space. Let's clean it!-->
<!--                    <div class="time">17 Hours Ago</div>-->
<!--                  </div>-->
<!--                </a>-->
<!--                <a href="#" class="dropdown-item">-->
<!--                  <div class="dropdown-item-icon bg-info text-white">-->
<!--                    <i class="fas fa-bell"></i>-->
<!--                  </div>-->
<!--                  <div class="dropdown-item-desc">-->
<!--                    Welcome to Stisla template!-->
<!--                    <div class="time">Yesterday</div>-->
<!--                  </div>-->
<!--                </a>-->
              </div>
              <div class="dropdown-footer text-center">
                <a href="{% url 'notify:notify_list' %}">Посмотреть все <i class="fas fa-chevron-right"></i></a>
              </div>
            </div>
          </li>
          <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
              {% if user.avatar %}
                  <img alt="image" src="/media/{{ user.avatar }}" class="rounded-circle mr-1" style="height: 30px;width: 30px;">
                  {% else %}
                  <img alt="image" src="{% static 'assets/img/avatar/avatar-1.png' %}" class="rounded-circle mr-1">
                  {% endif %}
            <div class="d-sm-none d-lg-inline-block">Hi, {{ user.username }}</div></a>
            <div class="dropdown-menu dropdown-menu-right">
              <a href="{% url 'auth:profile' %}" class="dropdown-item has-icon">
                <i class="far fa-user"></i> Профиль
              </a>
                {% if user.is_staff %}
                    <a href="{% url 'admin:index' %}" class="dropdown-item has-icon">
                <i class="fa-regular fa-lock"></i> Админка
              </a>
                    {% endif %}
              <a href="{% url 'posts:post_list' %}" class="dropdown-item has-icon">
                <i class="fas fa-bolt"></i> Посты
              </a>
              {% if user.is_staff %}
              <a href="{% url 'posts:moderate_list' %}" class="dropdown-item has-icon">
                <i class="fas fa-bolt"></i> Модерация
              </a>
              {% endif %}
            <a href="{% url 'settings:help' %}" class="dropdown-item has-icon">
               <i class="fas fa-question"></i> Помощь
              </a>
              <div class="dropdown-divider"></div>
              <a href="{% url 'auth:logout' %}" class="dropdown-item has-icon text-danger">
                <i class="fas fa-sign-out-alt"></i> Выйти
              </a>
            </div>
          </li>
            {% else %}
               <ul class="navbar-nav">
            <li class="nav-item active"><a href="{% url 'auth:login' %}" class="nav-link">Войти</a></li>
            <li class="nav-item"><a href="{% url 'auth:register' %}" class="nav-link">Регистрация</a></li>
          </ul>
            {% endif %}
        </ul>
      </nav>

habr_proj/mainapp/templates/mainapp/includes/inc_icons_list.html
<ul style="list-style: none;display: flex;margin: 0;padding: 0;justify-content: space-between;
">
    <div style="display: flex">
        <li style="margin-right: 10px;"><i class="fas fa-comment"></i> <span>{{ post.get_comments_quantity }}</span>
        </li>

        <li style="margin-right: 10px;"><i class="fas fa-eye"></i> <span>{{ post.views }}</span></li>
    </div>
    <div>
        <li class="like" style="margin-right: 10px;" id="{{ post.uid }}" data-id="{{ post.uid }}">
            <i {% if user in post.get_user_like %}class="fas fa-heart fa-2x" {% else %}class="far fa-heart" {% endif %}
               data-id="{{ post.uid }}"></i>
            <span>{{ post.get_likes_quantity }}</span></li>
    </div>

</ul>