habr_proj/habr_proj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mainapp.views import Index, SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Index.as_view(), name='main'),
    path('search/', SearchView.as_view(), name='search'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('notify/', include('notifyapp.urls', namespace='notify')),
    path('subscribe/', include('subscribe.urls', namespace='subscribe')),
    path('settings/', include('settings.urls', namespace='settings')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

habr_proj/notifyapp/urls.py
from django.urls import path

from notifyapp.views import NotifyConfirmAllView, NotifyListView, NotifyReadView, NotifyDeleteView

app_name = 'notify'

urlpatterns = [
    path('allconfirm/', NotifyConfirmAllView.as_view(), name='confirm_all'),
    path('list/', NotifyListView.as_view(), name='notify_list'),
    path('read/<category>/<pk>/', NotifyReadView.as_view(), name='notify_read'),
    path('delete/<category>/<pk>/', NotifyDeleteView.as_view(), name='notify_delete')
]

habr_proj/posts/urls.py
from django.urls import path

from posts import views as posts
from posts.views import PostListCategoryView, CommentDeleteView, CommentUpdateView, PostModerateView, \
    PostModerateListView, like_or_dislike

app_name = 'posts'

urlpatterns = [
    path('create/', posts.PostCreateView.as_view(), name='post_create'),
    path('list/', posts.PostListView.as_view(), name='post_list'),
    path('delete/<pk>/', posts.PostDeleteView.as_view(), name='post_delete'),
    path('update/<pk>/', posts.PostUpdateView.as_view(), name='post_update'),
    path('publish/<pk>/', posts.PostPublishView.as_view(), name='post_publish'),

    path('detail/<pk>/', posts.PostDetailView.as_view(), name='post_detail'),
    path('category/<pk>/', PostListCategoryView.as_view(), name='post_category'),

    path('comment/delete/<pk>/', CommentDeleteView.as_view(), name='comment_delete'),
    path('comment/update/<pk>/', CommentUpdateView.as_view(), name='comment_update'),

    path('moderate/<pk>/<mod_result>/', PostModerateView.as_view(), name='post_moderate'),
    path('moderatelist/', PostModerateListView.as_view(), name='moderate_list'),

    path('likes/<pk>/', like_or_dislike, name='likes')
]

habr_proj/notifyapp/models.py
from uuid import uuid4

from django.db import models

from authapp.models import HabrUser
from posts.models import Posts, Comment, PostsLikes


class BaseNotification(models.Model):
    STATUS_CREATE = 'CR'
    STATUS_SEND_PROCESS = 'PR'
    STATUS_SEND_COMPLETED = 'CPT'
    STATUS_ERROR = 'ERR'

    SEND_STATUSES = (
        (STATUS_CREATE, 'Создано'),
        (STATUS_SEND_PROCESS, 'Процесс отправки'),
        (STATUS_SEND_COMPLETED, 'Отправка успешна'),
        (STATUS_ERROR, 'Ошибка отправки'),
    )

    CATEGORY_POST = 'PST'
    CATEGORY_LIKE = 'LK'
    CATEGORY_COMMENT = 'CMT'
    CATEGORY_USER = 'USR'
    CATEGORIES = (
        (CATEGORY_POST, 'Уведомления к постам'),
        (CATEGORY_LIKE, 'Уведомления к лайкам'),
        (CATEGORY_COMMENT, 'Уведомления к коментариям'),
        (CATEGORY_USER, 'Уведомления по учетной записи'),
    )

    uid = models.UUIDField(primary_key=True, default=uuid4)
    category = models.CharField(max_length=3, null=True, choices=CATEGORIES, verbose_name='Категория уведомлений')

    to_user = models.ForeignKey(
        HabrUser,
        on_delete=models.CASCADE,
        verbose_name='Пользователю'
    )
    post = models.ForeignKey(Posts, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Хаб')
    like = models.ForeignKey(PostsLikes, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Лайк')
    comment = models.ForeignKey(Comment, blank=True, null=True, on_delete=models.CASCADE, verbose_name='Комментарий')
    username = models.CharField(max_length=128, blank=True, null=True, verbose_name='Имя пользователя')
    notify_body = models.TextField(blank=True, verbose_name='Содержание уведомления')
    status_send = models.CharField(max_length=3, choices=SEND_STATUSES,
                                   default=STATUS_CREATE, verbose_name='Статус отпраки')
    status = models.CharField(max_length=3, blank=True, null=True)
    is_read = models.BooleanField(default=False, verbose_name='Прочитано')
    to_moder = models.BooleanField(default=False, verbose_name='Для модератора')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Обновлено')

    class Meta:
        abstract = True


class NotifyPostStatus(BaseNotification):
    POST_NEW = 'NEW'
    POST_TO_MODERATION = 'TO'
    POST_MODERATED = 'MOD'
    POST_BLOCKED = 'BLC'
    POST_DELETED = 'DEL'
    POST_STATUSES = (
        (POST_NEW, 'Поступил новый на модерацию'),
        (POST_TO_MODERATION, 'На модерации'),
        (POST_MODERATED, 'Прошел модерацию'),
        (POST_BLOCKED, 'Заблокирован (не прошел модерацию)'),
        (POST_DELETED, 'Удален'),
    )

    status = models.CharField(max_length=3, choices=POST_STATUSES,
                              default=POST_NEW, verbose_name='Статус хаба')

    class Meta:
        verbose_name = 'Уведомление по хабу'
        verbose_name_plural = 'Уведомления по хабам'


class NotifyLike(BaseNotification):
    status = models.CharField(max_length=3, blank=True, null=True)

    class Meta:
        verbose_name = 'Уведомление по лайкам'
        verbose_name_plural = 'Уведомления по лайкам'


class NotifyComment(BaseNotification):
    status = models.CharField(max_length=3, blank=True, null=True)

    class Meta:
        verbose_name = 'Уведомление по комментариям'
        verbose_name_plural = 'Уведомления по комментариям'


class NotifyUserStatus(BaseNotification):
    USER_REGISTER = 'REG'
    USER_ACTIVE = 'ACT'
    USER_BLOCKED = 'BLC'
    USER_DELETE = 'DEL'
    USER_STATUSES = (
        (USER_REGISTER, 'Пользователь зарегистрирован'),
        (USER_ACTIVE, 'Учетная  запись активирована'),
        (USER_BLOCKED, 'Учетная запись временно заблокирована'),
        (USER_DELETE, 'Учетная запись удалена'),
    )
    status = models.CharField(max_length=3, choices=USER_STATUSES,
                              default=USER_REGISTER, verbose_name='Статус пользователя')

    class Meta:
        verbose_name = 'Уведомление по пользователю'
        verbose_name_plural = 'Уведомления по пользователю'

habr_proj/notifyapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import DetailView, ListView, DeleteView

from notifyapp.models import NotifyUserStatus, NotifyPostStatus, NotifyLike, NotifyComment, BaseNotification
from posts.views import get_categories


def get_all_unread_notify(pk):
    post_query = NotifyPostStatus.objects.filter(is_read=False, to_user__pk=pk)
    like_query = NotifyLike.objects.filter(is_read=False, to_user__pk=pk)
    comment_query = NotifyComment.objects.filter(is_read=False, to_user__pk=pk)
    user_query = NotifyUserStatus.objects.filter(is_read=False, to_user__pk=pk)
    return post_query.union(like_query, comment_query, user_query).order_by('-created_at').count()


def get_all_notify(pk):
    post_query = NotifyPostStatus.objects.filter(to_user__pk=pk)
    like_query = NotifyLike.objects.filter(to_user__pk=pk)
    comment_query = NotifyComment.objects.filter(to_user__pk=pk)
    user_query = NotifyUserStatus.objects.filter(to_user__pk=pk)
    return post_query.union(like_query, comment_query, user_query).order_by('-created_at')


def get_notify(pk, category):
    categories = {
        'PST': NotifyPostStatus,
        'LK': NotifyLike,
        'CMT': NotifyComment,
        'USR': NotifyUserStatus
    }

    return categories[category].objects.filter(pk=pk)


class NotifyConfirmAllView(DetailView):

    def get_queryset(self):
        return get_all_notify(self.request.user.pk)

    def get(self, request, *args, **kwargs):
        notifications = self.get_queryset()
        for notify in notifications:
            notify.is_read = True
            notify.save()
        return HttpResponseRedirect(reverse('main'))


class NotifyListView(ListView):
    template_name = 'notifyapp/notify_list.html'

    def get_queryset(self):
        return get_all_notify(self.request.user.pk)

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data['title'] = f'Уведомления {self.request.user}'
        context_data['notify_list'] = self.get_queryset()
        context_data['categories'] = get_categories()
        context_data['notify'] = get_all_notify(pk=self.request.user.pk)[:5]
        context_data['notify_count'] = get_all_unread_notify(pk=self.request.user.pk)
        return context_data


class NotifyReadView(DetailView):

    def get_queryset(self):
        return get_notify(self.kwargs.get('pk'), self.kwargs.get('category'))

    def get(self, request, *args, **kwargs):
        notify = self.get_queryset().first()
        if not notify.is_read:
            notify.is_read = True
        else:
            notify.is_read = False
        notify.save()
        return HttpResponseRedirect(reverse('notify:notify_list'))


class NotifyDeleteView(DeleteView):

    def get_queryset(self):
        return get_notify(self.kwargs.get('pk'), self.kwargs.get('category'))

    def get(self, request, *args, **kwargs):
        notify = self.get_queryset().first()
        notify.delete()
        return HttpResponseRedirect(reverse('notify:notify_list'))

habr_proj/notifyapp/templates/notifyapp/notify_detail.html
{% extends 'mainapp/new_base.html' %}
{% load static %}

{% block content %}
    <section class="section">
        <div class="">
            <article class="article article-style-c">
                <div class="article-header">
                    <div class="article-details">
                        <div class="article-category"><a href="#">{{ notify_item.get_category_display }}</a>
                            <div class="bullet"></div>
                            <a href="#">{{ notify_item.created_at.date }}
                                в {{ notify_item.created_at.time.hour }}:{{notify_item.created_at.time.minute }}</a></div>
                        <p >
                            {{ notify_item.notify_body|safe }}</p>
                    </div>
                </div>
            </article>
        </div>
    </section>
{% endblock %}

habr_proj/notifyapp/templates/notifyapp/notify_list.html
{% extends 'mainapp/new_base.html' %}
{% load static %}

{% block content %}
    <section class="section">
        <section class="section"></section>
        <div class="section-header">
            <h1>Ваши уведомления, {% if user.first_name %}
                {{ user.first_name|title }}
            {% else %}
                Пользователь
            {% endif %}</h1>

            <div class="section-header-breadcrumb">
                <div class="breadcrumb-item active"><a href="{% url 'main' %}">Главная</a></div>
                <div class="breadcrumb-item">Ваши уведомления</div>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4>Все уведомления</h4>
                    </div>
                    <div class="card-body">
                        <div class="float-right">
                            <form>
                                <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search">
                                    <div class="input-group-append">
                                        <button class="btn btn-primary"><i class="fas fa-search"></i></button>
                                    </div>
                                </div>
                            </form>
                        </div>

                        <div class="clearfix mb-3"></div>

                        <div class="table-responsive">
                            <table class="table table-striped">
                                <tr>
                                    <th>Текст уведомления</th>
                                    <th>Дата создания</th>
                                    <th>Статус отправки</th>
                                    <th>Состояние</th>
                                </tr>

                                {% for item in notify_list %}
                                    <tr class="dropdown-item-unread">
                                        <td>{{ item.notify_body }}
                                            <div class="table-links">
                                                <a href="{% url 'notify:notify_read' item.category item.pk %}">
                                                    {% if item.is_read %}
                                                    Отметить как не прочитанное
                                                    {% else %}
                                                    Отметить как прочитанное
                                                    {% endif %}
                                                </a>
                                                <div class="bullet"></div>
                                                {% if item.category == 'PST' %}
                                                <a href="{% url 'posts:post_detail' item.post.pk %}">Просмотреть Хаб</a>
                                                {% endif %}
                                                <div class="bullet"></div>
                                                <a href="{% url 'notify:notify_delete' item.category item.pk %}" class="text-danger">Удалить</a>
                                            </div>
                                        </td>

                                        <td>{{ item.created_at }}</td>
                                        <td>
                                            {{ item.get_status_send_display }}
                                        </td>
                                        <td>
                                            {% if item.is_read %}
                                                Просмотрено
                                            {% else %}
                                                Не просмотрено
                                            {% endif %}
                                        </td>

                                    </tr>
                                {% endfor %}
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}